name: MateriaList CI

env:
  DATABASE_FOLDER: ${{ vars.DATABASE_FOLDER }}
  DATABASE_FILE: ${{ vars.DATABASE_FILE }}
  LOG_LEVEL: ${{ vars.LOG_LEVEL }}

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "npm"

    - name: Build
      env:
        NODE_ENV: ${{ vars.NODE_ENV }}
      run: |
        npm ci --no-fund --no-audit
        npm run build
    
